name: CI Build

on:
  push:
    branches: [ main, solution ]
  pull_request:
    branches: [ main, solution ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up JDK 17
        uses: actions/setup-java@v6
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up SBT
        uses: sbt/setup-sbt@v1

      - name: Compile and Test
        run: sbt compile test
