name: CI Build

on:
  push:
    branches: [ main, solution ]
  pull_request:
    branches: [ main, solution ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up SBT
        uses: sbt/setup-sbt@v1

      - name: Compile and Test
        run: sbt compile test

      - name: Stage Application
        run: sbt stage

      - name: Run Pipeline E2E Test
        run: |
          ./target/universal/stage/bin/scio-quickstart --input-file=./data/sample.txt --output-file=tmp/out --num-words=10
          test -f tmp/out/part-00000-of-00001.txt
          echo "Pipeline executed successfully and output file verified!"
